### ISSUE TITLE
Issue with No terminal matches

### ISSUE THREAD

**Issue by franramb** [opendatadiscovery/odd-glue-adapter#9]
I am trying to ingest the metadata of glue but I am getting this error with varchar (x) and decimal (x, y) fields:

```
[2021-12-29 15:51:19,018] WARNING in __init__: There was an error during type parsing. Column name: "area_id". Table oddrn: "XXXXXXXXXXXXXX". Reason: "No terminal matches '(' in the current parser context, at line 1 col 8


varchar(3)

       ^

Expected one of: 

* MORETHAN

* COMMA

* FIELD_NAME
```

**Comment by DementevNikita** [comment]
Hey there, @franramb!

Thanks for reporting this issue! We'll look into that and get back to you as soon as possible

**Comment by DementevNikita** [comment]
Hey @franramb, thank you for your patience! Sorry it took so long

The issue was in the lark grammar we use to parse fields' types coming from Glue API. It didn't support varchars and decimals with length/precision+scale parameters.

Please try [0.1.1 release](https://github.com/opendatadiscovery/odd-glue-adapter/pkgs/container/adapters%2Fodd-glue-adapter/12763693?tag=0.1.1), it should be fixed in there. If the problem remains, please don't hesitate to reopen this issue or write directly to us in [ODD Slack namespace](https://go.opendatadiscovery.org/slack).
